require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ArticulocompsController do

  # This should return the minimal set of attributes required to create a valid
  # Articulocomp. As you add validations to Articulocomp, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all articulocomps as @articulocomps" do
      articulocomp = Articulocomp.create! valid_attributes
      get :index
      assigns(:articulocomps).should eq([articulocomp])
    end
  end

  describe "GET show" do
    it "assigns the requested articulocomp as @articulocomp" do
      articulocomp = Articulocomp.create! valid_attributes
      get :show, :id => articulocomp.id
      assigns(:articulocomp).should eq(articulocomp)
    end
  end

  describe "GET new" do
    it "assigns a new articulocomp as @articulocomp" do
      get :new
      assigns(:articulocomp).should be_a_new(Articulocomp)
    end
  end

  describe "GET edit" do
    it "assigns the requested articulocomp as @articulocomp" do
      articulocomp = Articulocomp.create! valid_attributes
      get :edit, :id => articulocomp.id
      assigns(:articulocomp).should eq(articulocomp)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Articulocomp" do
        expect {
          post :create, :articulocomp => valid_attributes
        }.to change(Articulocomp, :count).by(1)
      end

      it "assigns a newly created articulocomp as @articulocomp" do
        post :create, :articulocomp => valid_attributes
        assigns(:articulocomp).should be_a(Articulocomp)
        assigns(:articulocomp).should be_persisted
      end

      it "redirects to the created articulocomp" do
        post :create, :articulocomp => valid_attributes
        response.should redirect_to(Articulocomp.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved articulocomp as @articulocomp" do
        # Trigger the behavior that occurs when invalid params are submitted
        Articulocomp.any_instance.stub(:save).and_return(false)
        post :create, :articulocomp => {}
        assigns(:articulocomp).should be_a_new(Articulocomp)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Articulocomp.any_instance.stub(:save).and_return(false)
        post :create, :articulocomp => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested articulocomp" do
        articulocomp = Articulocomp.create! valid_attributes
        # Assuming there are no other articulocomps in the database, this
        # specifies that the Articulocomp created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Articulocomp.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => articulocomp.id, :articulocomp => {'these' => 'params'}
      end

      it "assigns the requested articulocomp as @articulocomp" do
        articulocomp = Articulocomp.create! valid_attributes
        put :update, :id => articulocomp.id, :articulocomp => valid_attributes
        assigns(:articulocomp).should eq(articulocomp)
      end

      it "redirects to the articulocomp" do
        articulocomp = Articulocomp.create! valid_attributes
        put :update, :id => articulocomp.id, :articulocomp => valid_attributes
        response.should redirect_to(articulocomp)
      end
    end

    describe "with invalid params" do
      it "assigns the articulocomp as @articulocomp" do
        articulocomp = Articulocomp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Articulocomp.any_instance.stub(:save).and_return(false)
        put :update, :id => articulocomp.id, :articulocomp => {}
        assigns(:articulocomp).should eq(articulocomp)
      end

      it "re-renders the 'edit' template" do
        articulocomp = Articulocomp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Articulocomp.any_instance.stub(:save).and_return(false)
        put :update, :id => articulocomp.id, :articulocomp => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested articulocomp" do
      articulocomp = Articulocomp.create! valid_attributes
      expect {
        delete :destroy, :id => articulocomp.id
      }.to change(Articulocomp, :count).by(-1)
    end

    it "redirects to the articulocomps list" do
      articulocomp = Articulocomp.create! valid_attributes
      delete :destroy, :id => articulocomp.id
      response.should redirect_to(articulocomps_url)
    end
  end

end
