require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DomiciliosController do

  # This should return the minimal set of attributes required to create a valid
  # Domicilio. As you add validations to Domicilio, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all domicilios as @domicilios" do
      domicilio = Domicilio.create! valid_attributes
      get :index
      assigns(:domicilios).should eq([domicilio])
    end
  end

  describe "GET show" do
    it "assigns the requested domicilio as @domicilio" do
      domicilio = Domicilio.create! valid_attributes
      get :show, :id => domicilio.id
      assigns(:domicilio).should eq(domicilio)
    end
  end

  describe "GET new" do
    it "assigns a new domicilio as @domicilio" do
      get :new
      assigns(:domicilio).should be_a_new(Domicilio)
    end
  end

  describe "GET edit" do
    it "assigns the requested domicilio as @domicilio" do
      domicilio = Domicilio.create! valid_attributes
      get :edit, :id => domicilio.id
      assigns(:domicilio).should eq(domicilio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Domicilio" do
        expect {
          post :create, :domicilio => valid_attributes
        }.to change(Domicilio, :count).by(1)
      end

      it "assigns a newly created domicilio as @domicilio" do
        post :create, :domicilio => valid_attributes
        assigns(:domicilio).should be_a(Domicilio)
        assigns(:domicilio).should be_persisted
      end

      it "redirects to the created domicilio" do
        post :create, :domicilio => valid_attributes
        response.should redirect_to(Domicilio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved domicilio as @domicilio" do
        # Trigger the behavior that occurs when invalid params are submitted
        Domicilio.any_instance.stub(:save).and_return(false)
        post :create, :domicilio => {}
        assigns(:domicilio).should be_a_new(Domicilio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Domicilio.any_instance.stub(:save).and_return(false)
        post :create, :domicilio => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested domicilio" do
        domicilio = Domicilio.create! valid_attributes
        # Assuming there are no other domicilios in the database, this
        # specifies that the Domicilio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Domicilio.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => domicilio.id, :domicilio => {'these' => 'params'}
      end

      it "assigns the requested domicilio as @domicilio" do
        domicilio = Domicilio.create! valid_attributes
        put :update, :id => domicilio.id, :domicilio => valid_attributes
        assigns(:domicilio).should eq(domicilio)
      end

      it "redirects to the domicilio" do
        domicilio = Domicilio.create! valid_attributes
        put :update, :id => domicilio.id, :domicilio => valid_attributes
        response.should redirect_to(domicilio)
      end
    end

    describe "with invalid params" do
      it "assigns the domicilio as @domicilio" do
        domicilio = Domicilio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Domicilio.any_instance.stub(:save).and_return(false)
        put :update, :id => domicilio.id, :domicilio => {}
        assigns(:domicilio).should eq(domicilio)
      end

      it "re-renders the 'edit' template" do
        domicilio = Domicilio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Domicilio.any_instance.stub(:save).and_return(false)
        put :update, :id => domicilio.id, :domicilio => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested domicilio" do
      domicilio = Domicilio.create! valid_attributes
      expect {
        delete :destroy, :id => domicilio.id
      }.to change(Domicilio, :count).by(-1)
    end

    it "redirects to the domicilios list" do
      domicilio = Domicilio.create! valid_attributes
      delete :destroy, :id => domicilio.id
      response.should redirect_to(domicilios_url)
    end
  end

end
