require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ImpuestosController do

  # This should return the minimal set of attributes required to create a valid
  # Impuesto. As you add validations to Impuesto, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all impuestos as @impuestos" do
      impuesto = Impuesto.create! valid_attributes
      get :index
      assigns(:impuestos).should eq([impuesto])
    end
  end

  describe "GET show" do
    it "assigns the requested impuesto as @impuesto" do
      impuesto = Impuesto.create! valid_attributes
      get :show, :id => impuesto.id
      assigns(:impuesto).should eq(impuesto)
    end
  end

  describe "GET new" do
    it "assigns a new impuesto as @impuesto" do
      get :new
      assigns(:impuesto).should be_a_new(Impuesto)
    end
  end

  describe "GET edit" do
    it "assigns the requested impuesto as @impuesto" do
      impuesto = Impuesto.create! valid_attributes
      get :edit, :id => impuesto.id
      assigns(:impuesto).should eq(impuesto)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Impuesto" do
        expect {
          post :create, :impuesto => valid_attributes
        }.to change(Impuesto, :count).by(1)
      end

      it "assigns a newly created impuesto as @impuesto" do
        post :create, :impuesto => valid_attributes
        assigns(:impuesto).should be_a(Impuesto)
        assigns(:impuesto).should be_persisted
      end

      it "redirects to the created impuesto" do
        post :create, :impuesto => valid_attributes
        response.should redirect_to(Impuesto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved impuesto as @impuesto" do
        # Trigger the behavior that occurs when invalid params are submitted
        Impuesto.any_instance.stub(:save).and_return(false)
        post :create, :impuesto => {}
        assigns(:impuesto).should be_a_new(Impuesto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Impuesto.any_instance.stub(:save).and_return(false)
        post :create, :impuesto => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested impuesto" do
        impuesto = Impuesto.create! valid_attributes
        # Assuming there are no other impuestos in the database, this
        # specifies that the Impuesto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Impuesto.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => impuesto.id, :impuesto => {'these' => 'params'}
      end

      it "assigns the requested impuesto as @impuesto" do
        impuesto = Impuesto.create! valid_attributes
        put :update, :id => impuesto.id, :impuesto => valid_attributes
        assigns(:impuesto).should eq(impuesto)
      end

      it "redirects to the impuesto" do
        impuesto = Impuesto.create! valid_attributes
        put :update, :id => impuesto.id, :impuesto => valid_attributes
        response.should redirect_to(impuesto)
      end
    end

    describe "with invalid params" do
      it "assigns the impuesto as @impuesto" do
        impuesto = Impuesto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Impuesto.any_instance.stub(:save).and_return(false)
        put :update, :id => impuesto.id, :impuesto => {}
        assigns(:impuesto).should eq(impuesto)
      end

      it "re-renders the 'edit' template" do
        impuesto = Impuesto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Impuesto.any_instance.stub(:save).and_return(false)
        put :update, :id => impuesto.id, :impuesto => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested impuesto" do
      impuesto = Impuesto.create! valid_attributes
      expect {
        delete :destroy, :id => impuesto.id
      }.to change(Impuesto, :count).by(-1)
    end

    it "redirects to the impuestos list" do
      impuesto = Impuesto.create! valid_attributes
      delete :destroy, :id => impuesto.id
      response.should redirect_to(impuestos_url)
    end
  end

end
