require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ListapreciosController do

  # This should return the minimal set of attributes required to create a valid
  # Listaprecio. As you add validations to Listaprecio, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all listaprecios as @listaprecios" do
      listaprecio = Listaprecio.create! valid_attributes
      get :index
      assigns(:listaprecios).should eq([listaprecio])
    end
  end

  describe "GET show" do
    it "assigns the requested listaprecio as @listaprecio" do
      listaprecio = Listaprecio.create! valid_attributes
      get :show, :id => listaprecio.id
      assigns(:listaprecio).should eq(listaprecio)
    end
  end

  describe "GET new" do
    it "assigns a new listaprecio as @listaprecio" do
      get :new
      assigns(:listaprecio).should be_a_new(Listaprecio)
    end
  end

  describe "GET edit" do
    it "assigns the requested listaprecio as @listaprecio" do
      listaprecio = Listaprecio.create! valid_attributes
      get :edit, :id => listaprecio.id
      assigns(:listaprecio).should eq(listaprecio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Listaprecio" do
        expect {
          post :create, :listaprecio => valid_attributes
        }.to change(Listaprecio, :count).by(1)
      end

      it "assigns a newly created listaprecio as @listaprecio" do
        post :create, :listaprecio => valid_attributes
        assigns(:listaprecio).should be_a(Listaprecio)
        assigns(:listaprecio).should be_persisted
      end

      it "redirects to the created listaprecio" do
        post :create, :listaprecio => valid_attributes
        response.should redirect_to(Listaprecio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved listaprecio as @listaprecio" do
        # Trigger the behavior that occurs when invalid params are submitted
        Listaprecio.any_instance.stub(:save).and_return(false)
        post :create, :listaprecio => {}
        assigns(:listaprecio).should be_a_new(Listaprecio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Listaprecio.any_instance.stub(:save).and_return(false)
        post :create, :listaprecio => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested listaprecio" do
        listaprecio = Listaprecio.create! valid_attributes
        # Assuming there are no other listaprecios in the database, this
        # specifies that the Listaprecio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Listaprecio.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => listaprecio.id, :listaprecio => {'these' => 'params'}
      end

      it "assigns the requested listaprecio as @listaprecio" do
        listaprecio = Listaprecio.create! valid_attributes
        put :update, :id => listaprecio.id, :listaprecio => valid_attributes
        assigns(:listaprecio).should eq(listaprecio)
      end

      it "redirects to the listaprecio" do
        listaprecio = Listaprecio.create! valid_attributes
        put :update, :id => listaprecio.id, :listaprecio => valid_attributes
        response.should redirect_to(listaprecio)
      end
    end

    describe "with invalid params" do
      it "assigns the listaprecio as @listaprecio" do
        listaprecio = Listaprecio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Listaprecio.any_instance.stub(:save).and_return(false)
        put :update, :id => listaprecio.id, :listaprecio => {}
        assigns(:listaprecio).should eq(listaprecio)
      end

      it "re-renders the 'edit' template" do
        listaprecio = Listaprecio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Listaprecio.any_instance.stub(:save).and_return(false)
        put :update, :id => listaprecio.id, :listaprecio => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested listaprecio" do
      listaprecio = Listaprecio.create! valid_attributes
      expect {
        delete :destroy, :id => listaprecio.id
      }.to change(Listaprecio, :count).by(-1)
    end

    it "redirects to the listaprecios list" do
      listaprecio = Listaprecio.create! valid_attributes
      delete :destroy, :id => listaprecio.id
      response.should redirect_to(listaprecios_url)
    end
  end

end
