require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PagoacreditosController do

  # This should return the minimal set of attributes required to create a valid
  # Pagoacredito. As you add validations to Pagoacredito, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all pagoacreditos as @pagoacreditos" do
      pagoacredito = Pagoacredito.create! valid_attributes
      get :index
      assigns(:pagoacreditos).should eq([pagoacredito])
    end
  end

  describe "GET show" do
    it "assigns the requested pagoacredito as @pagoacredito" do
      pagoacredito = Pagoacredito.create! valid_attributes
      get :show, :id => pagoacredito.id
      assigns(:pagoacredito).should eq(pagoacredito)
    end
  end

  describe "GET new" do
    it "assigns a new pagoacredito as @pagoacredito" do
      get :new
      assigns(:pagoacredito).should be_a_new(Pagoacredito)
    end
  end

  describe "GET edit" do
    it "assigns the requested pagoacredito as @pagoacredito" do
      pagoacredito = Pagoacredito.create! valid_attributes
      get :edit, :id => pagoacredito.id
      assigns(:pagoacredito).should eq(pagoacredito)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pagoacredito" do
        expect {
          post :create, :pagoacredito => valid_attributes
        }.to change(Pagoacredito, :count).by(1)
      end

      it "assigns a newly created pagoacredito as @pagoacredito" do
        post :create, :pagoacredito => valid_attributes
        assigns(:pagoacredito).should be_a(Pagoacredito)
        assigns(:pagoacredito).should be_persisted
      end

      it "redirects to the created pagoacredito" do
        post :create, :pagoacredito => valid_attributes
        response.should redirect_to(Pagoacredito.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pagoacredito as @pagoacredito" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pagoacredito.any_instance.stub(:save).and_return(false)
        post :create, :pagoacredito => {}
        assigns(:pagoacredito).should be_a_new(Pagoacredito)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pagoacredito.any_instance.stub(:save).and_return(false)
        post :create, :pagoacredito => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pagoacredito" do
        pagoacredito = Pagoacredito.create! valid_attributes
        # Assuming there are no other pagoacreditos in the database, this
        # specifies that the Pagoacredito created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pagoacredito.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => pagoacredito.id, :pagoacredito => {'these' => 'params'}
      end

      it "assigns the requested pagoacredito as @pagoacredito" do
        pagoacredito = Pagoacredito.create! valid_attributes
        put :update, :id => pagoacredito.id, :pagoacredito => valid_attributes
        assigns(:pagoacredito).should eq(pagoacredito)
      end

      it "redirects to the pagoacredito" do
        pagoacredito = Pagoacredito.create! valid_attributes
        put :update, :id => pagoacredito.id, :pagoacredito => valid_attributes
        response.should redirect_to(pagoacredito)
      end
    end

    describe "with invalid params" do
      it "assigns the pagoacredito as @pagoacredito" do
        pagoacredito = Pagoacredito.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pagoacredito.any_instance.stub(:save).and_return(false)
        put :update, :id => pagoacredito.id, :pagoacredito => {}
        assigns(:pagoacredito).should eq(pagoacredito)
      end

      it "re-renders the 'edit' template" do
        pagoacredito = Pagoacredito.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pagoacredito.any_instance.stub(:save).and_return(false)
        put :update, :id => pagoacredito.id, :pagoacredito => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pagoacredito" do
      pagoacredito = Pagoacredito.create! valid_attributes
      expect {
        delete :destroy, :id => pagoacredito.id
      }.to change(Pagoacredito, :count).by(-1)
    end

    it "redirects to the pagoacreditos list" do
      pagoacredito = Pagoacredito.create! valid_attributes
      delete :destroy, :id => pagoacredito.id
      response.should redirect_to(pagoacreditos_url)
    end
  end

end
