require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrecioartsController do

  # This should return the minimal set of attributes required to create a valid
  # Precioart. As you add validations to Precioart, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all precioarts as @precioarts" do
      precioart = Precioart.create! valid_attributes
      get :index
      assigns(:precioarts).should eq([precioart])
    end
  end

  describe "GET show" do
    it "assigns the requested precioart as @precioart" do
      precioart = Precioart.create! valid_attributes
      get :show, :id => precioart.id
      assigns(:precioart).should eq(precioart)
    end
  end

  describe "GET new" do
    it "assigns a new precioart as @precioart" do
      get :new
      assigns(:precioart).should be_a_new(Precioart)
    end
  end

  describe "GET edit" do
    it "assigns the requested precioart as @precioart" do
      precioart = Precioart.create! valid_attributes
      get :edit, :id => precioart.id
      assigns(:precioart).should eq(precioart)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Precioart" do
        expect {
          post :create, :precioart => valid_attributes
        }.to change(Precioart, :count).by(1)
      end

      it "assigns a newly created precioart as @precioart" do
        post :create, :precioart => valid_attributes
        assigns(:precioart).should be_a(Precioart)
        assigns(:precioart).should be_persisted
      end

      it "redirects to the created precioart" do
        post :create, :precioart => valid_attributes
        response.should redirect_to(Precioart.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved precioart as @precioart" do
        # Trigger the behavior that occurs when invalid params are submitted
        Precioart.any_instance.stub(:save).and_return(false)
        post :create, :precioart => {}
        assigns(:precioart).should be_a_new(Precioart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Precioart.any_instance.stub(:save).and_return(false)
        post :create, :precioart => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested precioart" do
        precioart = Precioart.create! valid_attributes
        # Assuming there are no other precioarts in the database, this
        # specifies that the Precioart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Precioart.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => precioart.id, :precioart => {'these' => 'params'}
      end

      it "assigns the requested precioart as @precioart" do
        precioart = Precioart.create! valid_attributes
        put :update, :id => precioart.id, :precioart => valid_attributes
        assigns(:precioart).should eq(precioart)
      end

      it "redirects to the precioart" do
        precioart = Precioart.create! valid_attributes
        put :update, :id => precioart.id, :precioart => valid_attributes
        response.should redirect_to(precioart)
      end
    end

    describe "with invalid params" do
      it "assigns the precioart as @precioart" do
        precioart = Precioart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Precioart.any_instance.stub(:save).and_return(false)
        put :update, :id => precioart.id, :precioart => {}
        assigns(:precioart).should eq(precioart)
      end

      it "re-renders the 'edit' template" do
        precioart = Precioart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Precioart.any_instance.stub(:save).and_return(false)
        put :update, :id => precioart.id, :precioart => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested precioart" do
      precioart = Precioart.create! valid_attributes
      expect {
        delete :destroy, :id => precioart.id
      }.to change(Precioart, :count).by(-1)
    end

    it "redirects to the precioarts list" do
      precioart = Precioart.create! valid_attributes
      delete :destroy, :id => precioart.id
      response.should redirect_to(precioarts_url)
    end
  end

end
