require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RenglonFacturasController do

  # This should return the minimal set of attributes required to create a valid
  # RenglonFactura. As you add validations to RenglonFactura, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all renglon_facturas as @renglon_facturas" do
      renglon_factura = RenglonFactura.create! valid_attributes
      get :index
      assigns(:renglon_facturas).should eq([renglon_factura])
    end
  end

  describe "GET show" do
    it "assigns the requested renglon_factura as @renglon_factura" do
      renglon_factura = RenglonFactura.create! valid_attributes
      get :show, :id => renglon_factura.id
      assigns(:renglon_factura).should eq(renglon_factura)
    end
  end

  describe "GET new" do
    it "assigns a new renglon_factura as @renglon_factura" do
      get :new
      assigns(:renglon_factura).should be_a_new(RenglonFactura)
    end
  end

  describe "GET edit" do
    it "assigns the requested renglon_factura as @renglon_factura" do
      renglon_factura = RenglonFactura.create! valid_attributes
      get :edit, :id => renglon_factura.id
      assigns(:renglon_factura).should eq(renglon_factura)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RenglonFactura" do
        expect {
          post :create, :renglon_factura => valid_attributes
        }.to change(RenglonFactura, :count).by(1)
      end

      it "assigns a newly created renglon_factura as @renglon_factura" do
        post :create, :renglon_factura => valid_attributes
        assigns(:renglon_factura).should be_a(RenglonFactura)
        assigns(:renglon_factura).should be_persisted
      end

      it "redirects to the created renglon_factura" do
        post :create, :renglon_factura => valid_attributes
        response.should redirect_to(RenglonFactura.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved renglon_factura as @renglon_factura" do
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonFactura.any_instance.stub(:save).and_return(false)
        post :create, :renglon_factura => {}
        assigns(:renglon_factura).should be_a_new(RenglonFactura)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonFactura.any_instance.stub(:save).and_return(false)
        post :create, :renglon_factura => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested renglon_factura" do
        renglon_factura = RenglonFactura.create! valid_attributes
        # Assuming there are no other renglon_facturas in the database, this
        # specifies that the RenglonFactura created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RenglonFactura.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => renglon_factura.id, :renglon_factura => {'these' => 'params'}
      end

      it "assigns the requested renglon_factura as @renglon_factura" do
        renglon_factura = RenglonFactura.create! valid_attributes
        put :update, :id => renglon_factura.id, :renglon_factura => valid_attributes
        assigns(:renglon_factura).should eq(renglon_factura)
      end

      it "redirects to the renglon_factura" do
        renglon_factura = RenglonFactura.create! valid_attributes
        put :update, :id => renglon_factura.id, :renglon_factura => valid_attributes
        response.should redirect_to(renglon_factura)
      end
    end

    describe "with invalid params" do
      it "assigns the renglon_factura as @renglon_factura" do
        renglon_factura = RenglonFactura.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonFactura.any_instance.stub(:save).and_return(false)
        put :update, :id => renglon_factura.id, :renglon_factura => {}
        assigns(:renglon_factura).should eq(renglon_factura)
      end

      it "re-renders the 'edit' template" do
        renglon_factura = RenglonFactura.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonFactura.any_instance.stub(:save).and_return(false)
        put :update, :id => renglon_factura.id, :renglon_factura => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested renglon_factura" do
      renglon_factura = RenglonFactura.create! valid_attributes
      expect {
        delete :destroy, :id => renglon_factura.id
      }.to change(RenglonFactura, :count).by(-1)
    end

    it "redirects to the renglon_facturas list" do
      renglon_factura = RenglonFactura.create! valid_attributes
      delete :destroy, :id => renglon_factura.id
      response.should redirect_to(renglon_facturas_url)
    end
  end

end
