require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RenglonNdcdetallesController do

  # This should return the minimal set of attributes required to create a valid
  # RenglonNdcdetalle. As you add validations to RenglonNdcdetalle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all renglon_ndcdetalles as @renglon_ndcdetalles" do
      renglon_ndcdetalle = RenglonNdcdetalle.create! valid_attributes
      get :index
      assigns(:renglon_ndcdetalles).should eq([renglon_ndcdetalle])
    end
  end

  describe "GET show" do
    it "assigns the requested renglon_ndcdetalle as @renglon_ndcdetalle" do
      renglon_ndcdetalle = RenglonNdcdetalle.create! valid_attributes
      get :show, :id => renglon_ndcdetalle.id
      assigns(:renglon_ndcdetalle).should eq(renglon_ndcdetalle)
    end
  end

  describe "GET new" do
    it "assigns a new renglon_ndcdetalle as @renglon_ndcdetalle" do
      get :new
      assigns(:renglon_ndcdetalle).should be_a_new(RenglonNdcdetalle)
    end
  end

  describe "GET edit" do
    it "assigns the requested renglon_ndcdetalle as @renglon_ndcdetalle" do
      renglon_ndcdetalle = RenglonNdcdetalle.create! valid_attributes
      get :edit, :id => renglon_ndcdetalle.id
      assigns(:renglon_ndcdetalle).should eq(renglon_ndcdetalle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RenglonNdcdetalle" do
        expect {
          post :create, :renglon_ndcdetalle => valid_attributes
        }.to change(RenglonNdcdetalle, :count).by(1)
      end

      it "assigns a newly created renglon_ndcdetalle as @renglon_ndcdetalle" do
        post :create, :renglon_ndcdetalle => valid_attributes
        assigns(:renglon_ndcdetalle).should be_a(RenglonNdcdetalle)
        assigns(:renglon_ndcdetalle).should be_persisted
      end

      it "redirects to the created renglon_ndcdetalle" do
        post :create, :renglon_ndcdetalle => valid_attributes
        response.should redirect_to(RenglonNdcdetalle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved renglon_ndcdetalle as @renglon_ndcdetalle" do
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNdcdetalle.any_instance.stub(:save).and_return(false)
        post :create, :renglon_ndcdetalle => {}
        assigns(:renglon_ndcdetalle).should be_a_new(RenglonNdcdetalle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNdcdetalle.any_instance.stub(:save).and_return(false)
        post :create, :renglon_ndcdetalle => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested renglon_ndcdetalle" do
        renglon_ndcdetalle = RenglonNdcdetalle.create! valid_attributes
        # Assuming there are no other renglon_ndcdetalles in the database, this
        # specifies that the RenglonNdcdetalle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RenglonNdcdetalle.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => renglon_ndcdetalle.id, :renglon_ndcdetalle => {'these' => 'params'}
      end

      it "assigns the requested renglon_ndcdetalle as @renglon_ndcdetalle" do
        renglon_ndcdetalle = RenglonNdcdetalle.create! valid_attributes
        put :update, :id => renglon_ndcdetalle.id, :renglon_ndcdetalle => valid_attributes
        assigns(:renglon_ndcdetalle).should eq(renglon_ndcdetalle)
      end

      it "redirects to the renglon_ndcdetalle" do
        renglon_ndcdetalle = RenglonNdcdetalle.create! valid_attributes
        put :update, :id => renglon_ndcdetalle.id, :renglon_ndcdetalle => valid_attributes
        response.should redirect_to(renglon_ndcdetalle)
      end
    end

    describe "with invalid params" do
      it "assigns the renglon_ndcdetalle as @renglon_ndcdetalle" do
        renglon_ndcdetalle = RenglonNdcdetalle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNdcdetalle.any_instance.stub(:save).and_return(false)
        put :update, :id => renglon_ndcdetalle.id, :renglon_ndcdetalle => {}
        assigns(:renglon_ndcdetalle).should eq(renglon_ndcdetalle)
      end

      it "re-renders the 'edit' template" do
        renglon_ndcdetalle = RenglonNdcdetalle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNdcdetalle.any_instance.stub(:save).and_return(false)
        put :update, :id => renglon_ndcdetalle.id, :renglon_ndcdetalle => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested renglon_ndcdetalle" do
      renglon_ndcdetalle = RenglonNdcdetalle.create! valid_attributes
      expect {
        delete :destroy, :id => renglon_ndcdetalle.id
      }.to change(RenglonNdcdetalle, :count).by(-1)
    end

    it "redirects to the renglon_ndcdetalles list" do
      renglon_ndcdetalle = RenglonNdcdetalle.create! valid_attributes
      delete :destroy, :id => renglon_ndcdetalle.id
      response.should redirect_to(renglon_ndcdetalles_url)
    end
  end

end
