require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RenglonNddndcsController do

  # This should return the minimal set of attributes required to create a valid
  # RenglonNddndc. As you add validations to RenglonNddndc, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all renglon_nddndcs as @renglon_nddndcs" do
      renglon_nddndc = RenglonNddndc.create! valid_attributes
      get :index
      assigns(:renglon_nddndcs).should eq([renglon_nddndc])
    end
  end

  describe "GET show" do
    it "assigns the requested renglon_nddndc as @renglon_nddndc" do
      renglon_nddndc = RenglonNddndc.create! valid_attributes
      get :show, :id => renglon_nddndc.id
      assigns(:renglon_nddndc).should eq(renglon_nddndc)
    end
  end

  describe "GET new" do
    it "assigns a new renglon_nddndc as @renglon_nddndc" do
      get :new
      assigns(:renglon_nddndc).should be_a_new(RenglonNddndc)
    end
  end

  describe "GET edit" do
    it "assigns the requested renglon_nddndc as @renglon_nddndc" do
      renglon_nddndc = RenglonNddndc.create! valid_attributes
      get :edit, :id => renglon_nddndc.id
      assigns(:renglon_nddndc).should eq(renglon_nddndc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RenglonNddndc" do
        expect {
          post :create, :renglon_nddndc => valid_attributes
        }.to change(RenglonNddndc, :count).by(1)
      end

      it "assigns a newly created renglon_nddndc as @renglon_nddndc" do
        post :create, :renglon_nddndc => valid_attributes
        assigns(:renglon_nddndc).should be_a(RenglonNddndc)
        assigns(:renglon_nddndc).should be_persisted
      end

      it "redirects to the created renglon_nddndc" do
        post :create, :renglon_nddndc => valid_attributes
        response.should redirect_to(RenglonNddndc.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved renglon_nddndc as @renglon_nddndc" do
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNddndc.any_instance.stub(:save).and_return(false)
        post :create, :renglon_nddndc => {}
        assigns(:renglon_nddndc).should be_a_new(RenglonNddndc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNddndc.any_instance.stub(:save).and_return(false)
        post :create, :renglon_nddndc => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested renglon_nddndc" do
        renglon_nddndc = RenglonNddndc.create! valid_attributes
        # Assuming there are no other renglon_nddndcs in the database, this
        # specifies that the RenglonNddndc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RenglonNddndc.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => renglon_nddndc.id, :renglon_nddndc => {'these' => 'params'}
      end

      it "assigns the requested renglon_nddndc as @renglon_nddndc" do
        renglon_nddndc = RenglonNddndc.create! valid_attributes
        put :update, :id => renglon_nddndc.id, :renglon_nddndc => valid_attributes
        assigns(:renglon_nddndc).should eq(renglon_nddndc)
      end

      it "redirects to the renglon_nddndc" do
        renglon_nddndc = RenglonNddndc.create! valid_attributes
        put :update, :id => renglon_nddndc.id, :renglon_nddndc => valid_attributes
        response.should redirect_to(renglon_nddndc)
      end
    end

    describe "with invalid params" do
      it "assigns the renglon_nddndc as @renglon_nddndc" do
        renglon_nddndc = RenglonNddndc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNddndc.any_instance.stub(:save).and_return(false)
        put :update, :id => renglon_nddndc.id, :renglon_nddndc => {}
        assigns(:renglon_nddndc).should eq(renglon_nddndc)
      end

      it "re-renders the 'edit' template" do
        renglon_nddndc = RenglonNddndc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNddndc.any_instance.stub(:save).and_return(false)
        put :update, :id => renglon_nddndc.id, :renglon_nddndc => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested renglon_nddndc" do
      renglon_nddndc = RenglonNddndc.create! valid_attributes
      expect {
        delete :destroy, :id => renglon_nddndc.id
      }.to change(RenglonNddndc, :count).by(-1)
    end

    it "redirects to the renglon_nddndcs list" do
      renglon_nddndc = RenglonNddndc.create! valid_attributes
      delete :destroy, :id => renglon_nddndc.id
      response.should redirect_to(renglon_nddndcs_url)
    end
  end

end
