require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RenglonNdcArticulosController do

  # This should return the minimal set of attributes required to create a valid
  # RenglonNdcArticulo. As you add validations to RenglonNdcArticulo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "comercializable" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RenglonNdcArticulosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all renglon_ndc_articulos as @renglon_ndc_articulos" do
      renglon_ndc_articulo = RenglonNdcArticulo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:renglon_ndc_articulos).should eq([renglon_ndc_articulo])
    end
  end

  describe "GET show" do
    it "assigns the requested renglon_ndc_articulo as @renglon_ndc_articulo" do
      renglon_ndc_articulo = RenglonNdcArticulo.create! valid_attributes
      get :show, {:id => renglon_ndc_articulo.to_param}, valid_session
      assigns(:renglon_ndc_articulo).should eq(renglon_ndc_articulo)
    end
  end

  describe "GET new" do
    it "assigns a new renglon_ndc_articulo as @renglon_ndc_articulo" do
      get :new, {}, valid_session
      assigns(:renglon_ndc_articulo).should be_a_new(RenglonNdcArticulo)
    end
  end

  describe "GET edit" do
    it "assigns the requested renglon_ndc_articulo as @renglon_ndc_articulo" do
      renglon_ndc_articulo = RenglonNdcArticulo.create! valid_attributes
      get :edit, {:id => renglon_ndc_articulo.to_param}, valid_session
      assigns(:renglon_ndc_articulo).should eq(renglon_ndc_articulo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RenglonNdcArticulo" do
        expect {
          post :create, {:renglon_ndc_articulo => valid_attributes}, valid_session
        }.to change(RenglonNdcArticulo, :count).by(1)
      end

      it "assigns a newly created renglon_ndc_articulo as @renglon_ndc_articulo" do
        post :create, {:renglon_ndc_articulo => valid_attributes}, valid_session
        assigns(:renglon_ndc_articulo).should be_a(RenglonNdcArticulo)
        assigns(:renglon_ndc_articulo).should be_persisted
      end

      it "redirects to the created renglon_ndc_articulo" do
        post :create, {:renglon_ndc_articulo => valid_attributes}, valid_session
        response.should redirect_to(RenglonNdcArticulo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved renglon_ndc_articulo as @renglon_ndc_articulo" do
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNdcArticulo.any_instance.stub(:save).and_return(false)
        post :create, {:renglon_ndc_articulo => { "comercializable" => "invalid value" }}, valid_session
        assigns(:renglon_ndc_articulo).should be_a_new(RenglonNdcArticulo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNdcArticulo.any_instance.stub(:save).and_return(false)
        post :create, {:renglon_ndc_articulo => { "comercializable" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested renglon_ndc_articulo" do
        renglon_ndc_articulo = RenglonNdcArticulo.create! valid_attributes
        # Assuming there are no other renglon_ndc_articulos in the database, this
        # specifies that the RenglonNdcArticulo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RenglonNdcArticulo.any_instance.should_receive(:update_attributes).with({ "comercializable" => "" })
        put :update, {:id => renglon_ndc_articulo.to_param, :renglon_ndc_articulo => { "comercializable" => "" }}, valid_session
      end

      it "assigns the requested renglon_ndc_articulo as @renglon_ndc_articulo" do
        renglon_ndc_articulo = RenglonNdcArticulo.create! valid_attributes
        put :update, {:id => renglon_ndc_articulo.to_param, :renglon_ndc_articulo => valid_attributes}, valid_session
        assigns(:renglon_ndc_articulo).should eq(renglon_ndc_articulo)
      end

      it "redirects to the renglon_ndc_articulo" do
        renglon_ndc_articulo = RenglonNdcArticulo.create! valid_attributes
        put :update, {:id => renglon_ndc_articulo.to_param, :renglon_ndc_articulo => valid_attributes}, valid_session
        response.should redirect_to(renglon_ndc_articulo)
      end
    end

    describe "with invalid params" do
      it "assigns the renglon_ndc_articulo as @renglon_ndc_articulo" do
        renglon_ndc_articulo = RenglonNdcArticulo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNdcArticulo.any_instance.stub(:save).and_return(false)
        put :update, {:id => renglon_ndc_articulo.to_param, :renglon_ndc_articulo => { "comercializable" => "invalid value" }}, valid_session
        assigns(:renglon_ndc_articulo).should eq(renglon_ndc_articulo)
      end

      it "re-renders the 'edit' template" do
        renglon_ndc_articulo = RenglonNdcArticulo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNdcArticulo.any_instance.stub(:save).and_return(false)
        put :update, {:id => renglon_ndc_articulo.to_param, :renglon_ndc_articulo => { "comercializable" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested renglon_ndc_articulo" do
      renglon_ndc_articulo = RenglonNdcArticulo.create! valid_attributes
      expect {
        delete :destroy, {:id => renglon_ndc_articulo.to_param}, valid_session
      }.to change(RenglonNdcArticulo, :count).by(-1)
    end

    it "redirects to the renglon_ndc_articulos list" do
      renglon_ndc_articulo = RenglonNdcArticulo.create! valid_attributes
      delete :destroy, {:id => renglon_ndc_articulo.to_param}, valid_session
      response.should redirect_to(renglon_ndc_articulos_url)
    end
  end

end
