require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RenglonNotadebitosController do

  # This should return the minimal set of attributes required to create a valid
  # RenglonNotadebito. As you add validations to RenglonNotadebito, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all renglon_notadebitos as @renglon_notadebitos" do
      renglon_notadebito = RenglonNotadebito.create! valid_attributes
      get :index
      assigns(:renglon_notadebitos).should eq([renglon_notadebito])
    end
  end

  describe "GET show" do
    it "assigns the requested renglon_notadebito as @renglon_notadebito" do
      renglon_notadebito = RenglonNotadebito.create! valid_attributes
      get :show, :id => renglon_notadebito.id
      assigns(:renglon_notadebito).should eq(renglon_notadebito)
    end
  end

  describe "GET new" do
    it "assigns a new renglon_notadebito as @renglon_notadebito" do
      get :new
      assigns(:renglon_notadebito).should be_a_new(RenglonNotadebito)
    end
  end

  describe "GET edit" do
    it "assigns the requested renglon_notadebito as @renglon_notadebito" do
      renglon_notadebito = RenglonNotadebito.create! valid_attributes
      get :edit, :id => renglon_notadebito.id
      assigns(:renglon_notadebito).should eq(renglon_notadebito)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RenglonNotadebito" do
        expect {
          post :create, :renglon_notadebito => valid_attributes
        }.to change(RenglonNotadebito, :count).by(1)
      end

      it "assigns a newly created renglon_notadebito as @renglon_notadebito" do
        post :create, :renglon_notadebito => valid_attributes
        assigns(:renglon_notadebito).should be_a(RenglonNotadebito)
        assigns(:renglon_notadebito).should be_persisted
      end

      it "redirects to the created renglon_notadebito" do
        post :create, :renglon_notadebito => valid_attributes
        response.should redirect_to(RenglonNotadebito.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved renglon_notadebito as @renglon_notadebito" do
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNotadebito.any_instance.stub(:save).and_return(false)
        post :create, :renglon_notadebito => {}
        assigns(:renglon_notadebito).should be_a_new(RenglonNotadebito)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNotadebito.any_instance.stub(:save).and_return(false)
        post :create, :renglon_notadebito => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested renglon_notadebito" do
        renglon_notadebito = RenglonNotadebito.create! valid_attributes
        # Assuming there are no other renglon_notadebitos in the database, this
        # specifies that the RenglonNotadebito created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RenglonNotadebito.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => renglon_notadebito.id, :renglon_notadebito => {'these' => 'params'}
      end

      it "assigns the requested renglon_notadebito as @renglon_notadebito" do
        renglon_notadebito = RenglonNotadebito.create! valid_attributes
        put :update, :id => renglon_notadebito.id, :renglon_notadebito => valid_attributes
        assigns(:renglon_notadebito).should eq(renglon_notadebito)
      end

      it "redirects to the renglon_notadebito" do
        renglon_notadebito = RenglonNotadebito.create! valid_attributes
        put :update, :id => renglon_notadebito.id, :renglon_notadebito => valid_attributes
        response.should redirect_to(renglon_notadebito)
      end
    end

    describe "with invalid params" do
      it "assigns the renglon_notadebito as @renglon_notadebito" do
        renglon_notadebito = RenglonNotadebito.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNotadebito.any_instance.stub(:save).and_return(false)
        put :update, :id => renglon_notadebito.id, :renglon_notadebito => {}
        assigns(:renglon_notadebito).should eq(renglon_notadebito)
      end

      it "re-renders the 'edit' template" do
        renglon_notadebito = RenglonNotadebito.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNotadebito.any_instance.stub(:save).and_return(false)
        put :update, :id => renglon_notadebito.id, :renglon_notadebito => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested renglon_notadebito" do
      renglon_notadebito = RenglonNotadebito.create! valid_attributes
      expect {
        delete :destroy, :id => renglon_notadebito.id
      }.to change(RenglonNotadebito, :count).by(-1)
    end

    it "redirects to the renglon_notadebitos list" do
      renglon_notadebito = RenglonNotadebito.create! valid_attributes
      delete :destroy, :id => renglon_notadebito.id
      response.should redirect_to(renglon_notadebitos_url)
    end
  end

end
