require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RenglonNotacreditosController do

  # This should return the minimal set of attributes required to create a valid
  # RenglonNotacredito. As you add validations to RenglonNotacredito, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all renglon_notacreditos as @renglon_notacreditos" do
      renglon_notacredito = RenglonNotacredito.create! valid_attributes
      get :index
      assigns(:renglon_notacreditos).should eq([renglon_notacredito])
    end
  end

  describe "GET show" do
    it "assigns the requested renglon_notacredito as @renglon_notacredito" do
      renglon_notacredito = RenglonNotacredito.create! valid_attributes
      get :show, :id => renglon_notacredito.id
      assigns(:renglon_notacredito).should eq(renglon_notacredito)
    end
  end

  describe "GET new" do
    it "assigns a new renglon_notacredito as @renglon_notacredito" do
      get :new
      assigns(:renglon_notacredito).should be_a_new(RenglonNotacredito)
    end
  end

  describe "GET edit" do
    it "assigns the requested renglon_notacredito as @renglon_notacredito" do
      renglon_notacredito = RenglonNotacredito.create! valid_attributes
      get :edit, :id => renglon_notacredito.id
      assigns(:renglon_notacredito).should eq(renglon_notacredito)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RenglonNotacredito" do
        expect {
          post :create, :renglon_notacredito => valid_attributes
        }.to change(RenglonNotacredito, :count).by(1)
      end

      it "assigns a newly created renglon_notacredito as @renglon_notacredito" do
        post :create, :renglon_notacredito => valid_attributes
        assigns(:renglon_notacredito).should be_a(RenglonNotacredito)
        assigns(:renglon_notacredito).should be_persisted
      end

      it "redirects to the created renglon_notacredito" do
        post :create, :renglon_notacredito => valid_attributes
        response.should redirect_to(RenglonNotacredito.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved renglon_notacredito as @renglon_notacredito" do
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNotacredito.any_instance.stub(:save).and_return(false)
        post :create, :renglon_notacredito => {}
        assigns(:renglon_notacredito).should be_a_new(RenglonNotacredito)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNotacredito.any_instance.stub(:save).and_return(false)
        post :create, :renglon_notacredito => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested renglon_notacredito" do
        renglon_notacredito = RenglonNotacredito.create! valid_attributes
        # Assuming there are no other renglon_notacreditos in the database, this
        # specifies that the RenglonNotacredito created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RenglonNotacredito.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => renglon_notacredito.id, :renglon_notacredito => {'these' => 'params'}
      end

      it "assigns the requested renglon_notacredito as @renglon_notacredito" do
        renglon_notacredito = RenglonNotacredito.create! valid_attributes
        put :update, :id => renglon_notacredito.id, :renglon_notacredito => valid_attributes
        assigns(:renglon_notacredito).should eq(renglon_notacredito)
      end

      it "redirects to the renglon_notacredito" do
        renglon_notacredito = RenglonNotacredito.create! valid_attributes
        put :update, :id => renglon_notacredito.id, :renglon_notacredito => valid_attributes
        response.should redirect_to(renglon_notacredito)
      end
    end

    describe "with invalid params" do
      it "assigns the renglon_notacredito as @renglon_notacredito" do
        renglon_notacredito = RenglonNotacredito.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNotacredito.any_instance.stub(:save).and_return(false)
        put :update, :id => renglon_notacredito.id, :renglon_notacredito => {}
        assigns(:renglon_notacredito).should eq(renglon_notacredito)
      end

      it "re-renders the 'edit' template" do
        renglon_notacredito = RenglonNotacredito.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonNotacredito.any_instance.stub(:save).and_return(false)
        put :update, :id => renglon_notacredito.id, :renglon_notacredito => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested renglon_notacredito" do
      renglon_notacredito = RenglonNotacredito.create! valid_attributes
      expect {
        delete :destroy, :id => renglon_notacredito.id
      }.to change(RenglonNotacredito, :count).by(-1)
    end

    it "redirects to the renglon_notacreditos list" do
      renglon_notacredito = RenglonNotacredito.create! valid_attributes
      delete :destroy, :id => renglon_notacredito.id
      response.should redirect_to(renglon_notacreditos_url)
    end
  end

end
