require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RenglonRecibosController do

  # This should return the minimal set of attributes required to create a valid
  # RenglonRecibo. As you add validations to RenglonRecibo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all renglon_recibos as @renglon_recibos" do
      renglon_recibo = RenglonRecibo.create! valid_attributes
      get :index
      assigns(:renglon_recibos).should eq([renglon_recibo])
    end
  end

  describe "GET show" do
    it "assigns the requested renglon_recibo as @renglon_recibo" do
      renglon_recibo = RenglonRecibo.create! valid_attributes
      get :show, :id => renglon_recibo.id
      assigns(:renglon_recibo).should eq(renglon_recibo)
    end
  end

  describe "GET new" do
    it "assigns a new renglon_recibo as @renglon_recibo" do
      get :new
      assigns(:renglon_recibo).should be_a_new(RenglonRecibo)
    end
  end

  describe "GET edit" do
    it "assigns the requested renglon_recibo as @renglon_recibo" do
      renglon_recibo = RenglonRecibo.create! valid_attributes
      get :edit, :id => renglon_recibo.id
      assigns(:renglon_recibo).should eq(renglon_recibo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RenglonRecibo" do
        expect {
          post :create, :renglon_recibo => valid_attributes
        }.to change(RenglonRecibo, :count).by(1)
      end

      it "assigns a newly created renglon_recibo as @renglon_recibo" do
        post :create, :renglon_recibo => valid_attributes
        assigns(:renglon_recibo).should be_a(RenglonRecibo)
        assigns(:renglon_recibo).should be_persisted
      end

      it "redirects to the created renglon_recibo" do
        post :create, :renglon_recibo => valid_attributes
        response.should redirect_to(RenglonRecibo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved renglon_recibo as @renglon_recibo" do
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonRecibo.any_instance.stub(:save).and_return(false)
        post :create, :renglon_recibo => {}
        assigns(:renglon_recibo).should be_a_new(RenglonRecibo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonRecibo.any_instance.stub(:save).and_return(false)
        post :create, :renglon_recibo => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested renglon_recibo" do
        renglon_recibo = RenglonRecibo.create! valid_attributes
        # Assuming there are no other renglon_recibos in the database, this
        # specifies that the RenglonRecibo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RenglonRecibo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => renglon_recibo.id, :renglon_recibo => {'these' => 'params'}
      end

      it "assigns the requested renglon_recibo as @renglon_recibo" do
        renglon_recibo = RenglonRecibo.create! valid_attributes
        put :update, :id => renglon_recibo.id, :renglon_recibo => valid_attributes
        assigns(:renglon_recibo).should eq(renglon_recibo)
      end

      it "redirects to the renglon_recibo" do
        renglon_recibo = RenglonRecibo.create! valid_attributes
        put :update, :id => renglon_recibo.id, :renglon_recibo => valid_attributes
        response.should redirect_to(renglon_recibo)
      end
    end

    describe "with invalid params" do
      it "assigns the renglon_recibo as @renglon_recibo" do
        renglon_recibo = RenglonRecibo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonRecibo.any_instance.stub(:save).and_return(false)
        put :update, :id => renglon_recibo.id, :renglon_recibo => {}
        assigns(:renglon_recibo).should eq(renglon_recibo)
      end

      it "re-renders the 'edit' template" do
        renglon_recibo = RenglonRecibo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RenglonRecibo.any_instance.stub(:save).and_return(false)
        put :update, :id => renglon_recibo.id, :renglon_recibo => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested renglon_recibo" do
      renglon_recibo = RenglonRecibo.create! valid_attributes
      expect {
        delete :destroy, :id => renglon_recibo.id
      }.to change(RenglonRecibo, :count).by(-1)
    end

    it "redirects to the renglon_recibos list" do
      renglon_recibo = RenglonRecibo.create! valid_attributes
      delete :destroy, :id => renglon_recibo.id
      response.should redirect_to(renglon_recibos_url)
    end
  end

end
