require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TipoclientesController do

  # This should return the minimal set of attributes required to create a valid
  # Tipocliente. As you add validations to Tipocliente, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tipoclientes as @tipoclientes" do
      tipocliente = Tipocliente.create! valid_attributes
      get :index
      assigns(:tipoclientes).should eq([tipocliente])
    end
  end

  describe "GET show" do
    it "assigns the requested tipocliente as @tipocliente" do
      tipocliente = Tipocliente.create! valid_attributes
      get :show, :id => tipocliente.id
      assigns(:tipocliente).should eq(tipocliente)
    end
  end

  describe "GET new" do
    it "assigns a new tipocliente as @tipocliente" do
      get :new
      assigns(:tipocliente).should be_a_new(Tipocliente)
    end
  end

  describe "GET edit" do
    it "assigns the requested tipocliente as @tipocliente" do
      tipocliente = Tipocliente.create! valid_attributes
      get :edit, :id => tipocliente.id
      assigns(:tipocliente).should eq(tipocliente)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tipocliente" do
        expect {
          post :create, :tipocliente => valid_attributes
        }.to change(Tipocliente, :count).by(1)
      end

      it "assigns a newly created tipocliente as @tipocliente" do
        post :create, :tipocliente => valid_attributes
        assigns(:tipocliente).should be_a(Tipocliente)
        assigns(:tipocliente).should be_persisted
      end

      it "redirects to the created tipocliente" do
        post :create, :tipocliente => valid_attributes
        response.should redirect_to(Tipocliente.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tipocliente as @tipocliente" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tipocliente.any_instance.stub(:save).and_return(false)
        post :create, :tipocliente => {}
        assigns(:tipocliente).should be_a_new(Tipocliente)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tipocliente.any_instance.stub(:save).and_return(false)
        post :create, :tipocliente => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tipocliente" do
        tipocliente = Tipocliente.create! valid_attributes
        # Assuming there are no other tipoclientes in the database, this
        # specifies that the Tipocliente created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tipocliente.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => tipocliente.id, :tipocliente => {'these' => 'params'}
      end

      it "assigns the requested tipocliente as @tipocliente" do
        tipocliente = Tipocliente.create! valid_attributes
        put :update, :id => tipocliente.id, :tipocliente => valid_attributes
        assigns(:tipocliente).should eq(tipocliente)
      end

      it "redirects to the tipocliente" do
        tipocliente = Tipocliente.create! valid_attributes
        put :update, :id => tipocliente.id, :tipocliente => valid_attributes
        response.should redirect_to(tipocliente)
      end
    end

    describe "with invalid params" do
      it "assigns the tipocliente as @tipocliente" do
        tipocliente = Tipocliente.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tipocliente.any_instance.stub(:save).and_return(false)
        put :update, :id => tipocliente.id, :tipocliente => {}
        assigns(:tipocliente).should eq(tipocliente)
      end

      it "re-renders the 'edit' template" do
        tipocliente = Tipocliente.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tipocliente.any_instance.stub(:save).and_return(false)
        put :update, :id => tipocliente.id, :tipocliente => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tipocliente" do
      tipocliente = Tipocliente.create! valid_attributes
      expect {
        delete :destroy, :id => tipocliente.id
      }.to change(Tipocliente, :count).by(-1)
    end

    it "redirects to the tipoclientes list" do
      tipocliente = Tipocliente.create! valid_attributes
      delete :destroy, :id => tipocliente.id
      response.should redirect_to(tipoclientes_url)
    end
  end

end
